# PUBLIC INTERFACE
# ─────────────────────────────────────────────────────────
# export_report_pdf(report_id: UUID) -> bytes
# ─────────────────────────────────────────────────────────
from __future__ import annotations

import base64
from datetime import UTC, datetime
from uuid import UUID

import structlog
from weasyprint import HTML

from app.core.database import get_supabase_admin
from app.services.export.chart_renderer import (
    render_heatmap,
    render_platform_activity,
    render_sentiment_chart,
)
from app.services.intelligence.react_tools import simulation_analytics
from app.services.intelligence.report_agent import clean_report_output

logger = structlog.get_logger()


def _b64_img(png_bytes: bytes) -> str:
    return f"data:image/png;base64,{base64.b64encode(png_bytes).decode()}"


def _adversarial_disclosure(simulation_id: str) -> dict:
    """The run's adversarial disclosure, read from the artifact.

    Read, never recomposed. The sentence is written once in
    `analysis_builder._adversarial_disclosure` so the viewer, the print page,
    the JSON export and this PDF cannot say four slightly different things about
    the same cohort.
    """
    from app.services.intelligence.analysis_builder import get_analysis

    artifact = (get_analysis(simulation_id) or {}).get("artifact") or {}
    return artifact.get("adversarial") or {"enabled": False}


async def export_report_pdf(report_id: UUID) -> bytes:
    """Generate PDF from a completed report."""
    admin = get_supabase_admin()

    report = admin.table("reports").select("*").eq(
        "id", str(report_id)
    ).single().execute().data

    sim = admin.table("simulations").select("*").eq(
        "id", report["simulation_id"]
    ).single().execute().data

    org = admin.table("organizations").select("name").eq(
        "id", report["organization_id"]
    ).single().execute().data

    sections = admin.table("report_sections").select("*").eq(
        "report_id", str(report_id)
    ).order("section_index").execute().data

    # Generate charts
    sentiment_data = await simulation_analytics(
        UUID(report["simulation_id"]), "sentiment_over_time"
    )
    sentiment_chart = ""
    curve = sentiment_data.data.get("sentiment_curve", {})
    if curve:
        timeline = [curve[k] for k in sorted(curve, key=int)]
        sentiment_chart = _b64_img(render_sentiment_chart(timeline))

    platform_data = await simulation_analytics(
        UUID(report["simulation_id"]), "platform_comparison"
    )
    platform_chart = ""
    pdata = platform_data.data.get("platform_events", {})
    if pdata:
        platform_chart = _b64_img(render_platform_activity(pdata))

    persona_data = await simulation_analytics(
        UUID(report["simulation_id"]), "persona_breakdown"
    )
    heatmap_chart = ""
    # Build simple heatmap from persona breakdown
    pbreakdown = persona_data.data.get("persona_events", {})
    if pbreakdown:
        heatmap_items = [
            {"persona_type": k, "platform": "all", "intensity": min(1.0, v / 50), "sentiment": 0.0}
            for k, v in pbreakdown.items()
        ]
        heatmap_chart = _b64_img(render_heatmap(heatmap_items))

    # Build HTML
    sections_html = ""
    for s in sections:
        content = clean_report_output(s.get("content") or "").replace("\n", "<br>")
        sections_html += f"""
        <div class="section">
            <h2>{s['title']}</h2>
            <div class="section-content">{content}</div>
        </div>
        """

    # PRD §4: adversarial agents are labelled synthetic in every report and
    # export. A PDF is the artefact that gets forwarded to a board or an
    # investor, so it is the one where an unlabelled hostile cohort does the
    # most damage — the recipient never saw the run being configured.
    adversarial_html = ""
    disclosure = _adversarial_disclosure(report["simulation_id"])
    if disclosure.get("enabled"):
        roles = disclosure.get("roles") or {}
        roles_line = (
            "<p><strong>Roles:</strong> "
            + ", ".join(f"{k.replace('_', ' ')} ({v})" for k, v in sorted(roles.items()))
            + "</p>"
            if roles
            else ""
        )
        adversarial_html = f"""
    <div class="section adversarial">
        <h2>Adversarial cohort disclosure</h2>
        <p>{disclosure.get('disclosure', '')}</p>
        {roles_line}
    </div>"""

    charts_html = ""
    if sentiment_chart:
        charts_html += f'<div class="chart"><img src="{sentiment_chart}"></div>'
    if platform_chart:
        charts_html += f'<div class="chart"><img src="{platform_chart}"></div>'
    if heatmap_chart:
        charts_html += f'<div class="chart"><img src="{heatmap_chart}"></div>'

    html_content = f"""<!DOCTYPE html>
<html>
<head>
<style>
    @page {{ margin: 2cm; @bottom-center {{ content: "{org['name']} — Generated by Saibyl | Page " counter(page); }} }}
    body {{ font-family: system-ui, -apple-system, sans-serif; color: #1A3A5C; line-height: 1.6; font-size: 11pt; }}
    .cover {{ text-align: center; padding: 120px 0 60px; page-break-after: always; }}
    .cover h1 {{ font-size: 28pt; color: #1A3A5C; margin-bottom: 10px; }}
    .cover .subtitle {{ font-size: 14pt; color: #666; }}
    .cover .date {{ font-size: 11pt; color: #999; margin-top: 30px; }}
    h2 {{ color: #2E6DA4; border-bottom: 2px solid #2E6DA4; padding-bottom: 5px; page-break-after: avoid; }}
    .section {{ page-break-inside: avoid; margin-bottom: 24px; }}
    .section-content {{ margin-top: 8px; }}
    .chart {{ text-align: center; margin: 20px 0; page-break-inside: avoid; }}
    .chart img {{ max-width: 100%; height: auto; }}
    .methodology {{ background: #F0F4FA; padding: 16px; border-radius: 6px; font-size: 10pt; }}
    .adversarial {{ background: #FDF6E3; border-left: 4px solid #C9A227; padding: 16px; border-radius: 6px; font-size: 10pt; }}
</style>
</head>
<body>
    <div class="cover">
        <h1>{report.get('title', 'Intelligence Report')}</h1>
        <div class="subtitle">{sim['name']}</div>
        <div class="subtitle">{org['name']}</div>
        <div class="date">{datetime.now(UTC).strftime('%B %d, %Y')}</div>
    </div>

    {sections_html}

    {charts_html}

    {adversarial_html}

    <div class="section methodology">
        <h2>Methodology</h2>
        <p><strong>Platforms:</strong> {', '.join(sim.get('platforms') or ['N/A'])}</p>
        <p><strong>Max rounds:</strong> {sim.get('max_rounds', 'N/A')}</p>
        <p><strong>Prediction goal:</strong> {sim.get('prediction_goal', 'N/A')}</p>
        <p><strong>Variants tested:</strong> {sim.get('variants') or 1}</p>
    </div>
</body>
</html>"""

    pdf_bytes = HTML(string=html_content).write_pdf()
    logger.info("pdf_exported", report_id=str(report_id), size=len(pdf_bytes))
    return pdf_bytes
