from __future__ import annotations

import re
from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator
from datetime import datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel

from app.services.refs import post_ref as _normalise_post_ref


class ReactionType(StrEnum):
    LIKE = "like"
    LOVE = "love"
    HAHA = "haha"
    WOW = "wow"
    SAD = "sad"
    ANGRY = "angry"
    DISLIKE = "dislike"
    REPOST = "repost"
    SHARE = "share"
    UPVOTE = "upvote"
    DOWNVOTE = "downvote"
    AWARD = "award"
    # LinkedIn's vocabulary. Present because the alternative was mapping all
    # four onto LIKE, which is what `_LINKEDIN_REACTIONS` used to do: every
    # `celebrate`, `support`, `insightful` and `curious` incremented the `like`
    # bucket, so the breakdown the adapter maintained had exactly one non-zero
    # key on every run and reported it as a finding.
    CELEBRATE = "celebrate"
    SUPPORT = "support"
    INSIGHTFUL = "insightful"
    CURIOUS = "curious"


# What an adapter may emit, grouped by how the propagation graph treats it.
#
# **These strings are persisted** in `simulation_events.event_type` and are read
# by the analysis pipeline, the exporters and the comparison API. They are a
# closed vocabulary, not free text — see `EventType` below, which is what stops
# a thirteenth adapter inventing a value the runner then misfiles.
POST_EVENT_TYPES = frozenset({"post"})
REPLY_EVENT_TYPES = frozenset({"comment", "react"})
# Directed at another agent rather than at a post: it neither mints a post id
# nor replies to one, so it takes no part in the graph.
DIRECTED_EVENT_TYPES = frozenset({"dm"})
KNOWN_EVENT_TYPES = POST_EVENT_TYPES | REPLY_EVENT_TYPES | DIRECTED_EVENT_TYPES

# The same vocabulary as a type, so pydantic rejects an unrecognised value at
# the moment an adapter constructs the event rather than in the runner, which
# used to classify anything it did not recognise as a post.
EventType = Literal["post", "comment", "react", "dm"]


class Post(BaseModel):
    id: str
    platform: str
    author_username: str
    content: str
    created_at: datetime
    metadata: dict = {}


class Comment(BaseModel):
    id: str
    post_id: str
    platform: str
    author_username: str
    content: str
    parent_comment_id: str | None = None
    created_at: datetime


class SimulationEvent(BaseModel):
    # Closed vocabulary — see EventType. It was an unconstrained `str` set
    # independently in twelve adapters, and the runner's classifier was a
    # *negative* allow-list: anything that was not a comment or a react was
    # treated as a post and claimed a post id, so a new event type would have
    # silently overwritten a real parent in the propagation graph.
    event_type: EventType

    # The agent's database id. This is what attributes an event to an agent.
    #
    # `agent_username` is a display handle generated by an LLM and is NOT an
    # identity. Asked for 100 handles the model returned 45 distinct ones — nine
    # agents called `mchen_itdir` — and because the runner mapped events back
    # through the username, all nine agents' events landed on one row and nine
    # independent observations counted as one in every confidence interval.
    #
    # Uniqueness is now enforced at generation and by a database constraint, but
    # identity does not depend on that holding: it rides on the id.
    agent_id: str | None = None
    agent_username: str

    platform: str
    round_number: int
    variant: str
    content: str | None = None
    target_id: str | None = None
    metadata: dict = {}
    timestamp: datetime


class BasePlatformAdapter(ABC):
    platform_id: str = ""
    platform_name: str = ""
    supports_reactions: bool = True
    supports_dms: bool = False
    max_post_length: int = 1000
    max_comment_length: int = 500

    # Agent memory: tracks each agent's actions across rounds
    _agent_history: dict[str, list[str]]

    # The question that opened the conversation — `simulations.prediction_goal`,
    # or the arena's variant copy. Empty until set_topic() is called.
    #
    # **This is the framing, not the subject.** It was both until 2026-08-04,
    # which is the defect `_subject_brief` below exists to close.
    _topic: str = ""

    # The subject itself: the team's uploaded material, distilled once per run
    # into a bounded brief. Empty on a run whose project uploaded nothing usable,
    # and on every run created before the distillation existed.
    _subject_brief: str = ""

    # Material the team published alongside the subject, in the inoculation
    # loop's re-simulation. Empty on every ordinary run.
    _pre_positioned: str = ""

    # What buyers raised in this team's OWN earlier runs, as things to check.
    # Empty on a first run, which is the normal case and not an error — see
    # `services/engine/grounding.py`.
    _grounding: str = ""

    def _init_history(self) -> None:
        self._agent_history = {}

    def set_topic(self, config: dict) -> None:
        """Capture the simulation's subject, its framing, and pre-positioned material.

        All three arrive through the run config, and all three are read by
        `topic_block()`, which every adapter already calls. That is deliberate:
        the inoculation loop needed the assets in front of all twelve adapters,
        and adding a hook to twelve `initialize` implementations is twelve
        chances to miss one. The subject brief arrives the same way for the same
        reason — there is no per-adapter path and there must not be one.
        """
        config = config or {}
        self._topic = config.get("prediction_goal", "") or ""
        self._subject_brief = config.get("subject_brief", "") or ""
        self._pre_positioned = config.get("pre_positioned", "") or ""
        # Grounding rides the same path for the same reason the two above do:
        # there is no per-adapter hook and there must not be one.
        self._grounding = config.get("grounding", "") or ""

    def topic_block(self, feed_is_empty: bool = False) -> str:
        """What every action prompt must carry: the subject, and its framing.

        Until this existed, no adapter told its agents what the simulation was
        about: `prediction_goal` was stored in `self._config` by all twelve and
        read by none. The topic reached agents only through the persona bio,
        which is generated from it — so the simulation depended on the bio
        generator succeeding, and produced silent agents when it did not.

        **The second half of that defect survived the fix.** The block carried
        `prediction_goal` and nothing else, so a founder who uploaded a
        14,028-character deck had their agents react to the one-line description
        of it. The deck reached the *agent-generation* prompt at
        `doc_context[:2000]`, where it shaped who the agents were, and never
        reached the conversation those agents then had.

        So the two are now distinct and both present:

        - **The subject** is `_subject_brief` — the uploaded material distilled
          once per run into a bounded brief (`services/intelligence/
          subject_brief.py`). This is the thing agents react to.
        - **The framing** is `_topic` — the founder's description, which is the
          question that opens the conversation rather than the thing being
          discussed.

        The distinction is legible in the prompt because an agent that cannot
        tell them apart argues with the question instead of the product. With no
        brief — a project with no uploads, or a run that predates this — the
        framing becomes the subject again, which is exactly the old behaviour and
        is why a document-free run still works.

        The empty-feed nudge is the other half of this block. On round one
        nobody has posted, and "observe before engaging" is what a careful person
        actually does — so every agent picks NOTHING, the feed stays empty, and
        the run deadlocks at zero events for however many rounds it was given.
        """
        if not self._topic and not self._subject_brief:
            return ""

        if self._subject_brief:
            block = (
                "THE SUBJECT — this is what you are reacting to:\n"
                f"{self._subject_brief.strip()}\n\n"
            )
            if self._topic:
                block += (
                    "WHAT STARTED THE CONVERSATION — the question being asked "
                    f"about it:\n{self._topic.strip()}\n\n"
                )
        else:
            block = f"The conversation is about: {self._topic.strip()}\n\n"

        # Pre-positioned, not posted. The material is published alongside the
        # subject and available to every agent from round one, which is what
        # "pre-position this before launch" actually means. Injecting it as a
        # feed post would model somebody dropping the FAQ into the thread — a
        # different intervention, reaching only the agents whose feed slice
        # happened to include it.
        if self._pre_positioned:
            block += self._pre_positioned

        # What this team's earlier rooms raised. Placed AFTER the subject and
        # the framing so it reads as background rather than as the question —
        # and phrased by `grounding_prompt_section` as things to check, never
        # conclusions to repeat. A room told "buyers object to X" objects to X
        # and the run becomes a mirror of its own prompt, which is the
        # correlated-hallucination failure the whole product is judged on.
        if self._grounding:
            block += self._grounding.rstrip() + "\n\n"

        if feed_is_empty:
            block += (
                "The feed is empty — you are among the first to react. Do not "
                "wait for someone else to start; POST your own reaction to the "
                "subject above.\n\n"
            )
        return block

    def record_action(self, agent_key: str, round_num: int, summary: str) -> None:
        """Record an agent's action for memory across rounds.

        `agent_key` must be the agent's **id**, not its username. Keying memory
        on a display handle let colliding agents read each other's history —
        nine agents sharing one handle shared one memory and behaved as a single
        confused actor.
        """
        self._agent_history.setdefault(agent_key, []).append(f"[R{round_num}] {summary}")

    def get_agent_memory(self, agent_key: str, max_items: int = 10) -> str:
        """Formatted history of one agent's previous actions. Keyed on id."""
        history = self._agent_history.get(agent_key, [])
        if not history:
            return ""
        recent = history[-max_items:]
        return "Your previous actions:\n" + "\n".join(recent) + "\n\n"

    @staticmethod
    def agent_key(agent: dict) -> str:
        """Stable identity for an agent dict handed to an adapter.

        Falls back to the username only when no id was supplied, which happens
        in adapter unit tests and nowhere in the live pipeline.
        """
        return agent.get("agent_id") or agent.get("username", "")

    @staticmethod
    def post_ref(raw: object) -> str:
        """A post id an agent typed back, stripped of what it wrapped around it.

        **Every adapter renders its feed as `[<id>] @author: text` and then asks
        for `COMMENT <post_id>: …`. The model copies the id along with the
        brackets it was shown in — inconsistently.** So `post_id` arrives as
        `[a1b2c3]` about four times in five and as `a1b2c3` the rest, and every
        `if p.id == post_id` in this package silently fails on the first form.

        The consequences were live for the whole of V1: reactions never found
        their post, so `upvotes`/`likes` never incremented, so `_hot_score`
        ranked every feed by recency alone. Nothing errored. The feed simply was
        not the feed the design describes, on every run ever made.

        Found on 2026-08-04 by the first run that compared a reference against a
        stored id — 193 of 193 replies failed to resolve — which is the general
        lesson: a value nothing checks is a value nothing is enforcing.

        Use this at the point an id arrives from a model, before comparing it to
        anything.

        Delegates to `app.services.refs.post_ref` rather than repeating the
        strip set. It *was* repeated — as a literal here and a second literal in
        the runner — and the two had already drifted by one character. That
        drift is precisely how the 193-of-193 failure comes back with nothing in
        the logs, so there is one definition and this is not it.
        """
        return _normalise_post_ref(raw)

    @staticmethod
    def action_ref(line: str) -> str:
        """The post id out of a `VERB <post_id>` action line.

        Every adapter's prompt asks for bare verb lines — `UPVOTE <post_id>`,
        `LIKE <post_id>`, `SHARE <post_id>` — and every adapter used to read the
        id as `line.split(maxsplit=1)[1].strip()`, which is *the rest of the
        line*, not the id. A model that volunteers a reason —
        `UPVOTE [a1b2c3] — solid point`, which is exactly what a persona prompt
        encourages — yielded `a1b2c3] — solid point`.

        `post_ref` could not repair that: it strips edges by design, so a stray
        separator *inside* the value stays visible rather than being silently
        healed into a plausible different id. The repair has to happen where the
        line is split, so it happens here, once, for all twelve adapters.

        Returns "" when the line carries no id, which callers already treat as
        "no action".
        """
        match = re.match(r"^\s*\S+\s+(\S+)", str(line or ""))
        return _normalise_post_ref(match.group(1)) if match else ""

    @abstractmethod
    async def initialize(self, config: dict, agents: list) -> None:
        """Set up platform state, assign agents."""

    @abstractmethod
    async def run_round(self, round_number: int) -> AsyncGenerator[SimulationEvent, None]:
        """Execute one simulation round. Yields events as they occur."""

    @abstractmethod
    async def get_feed(self, agent_username: str) -> list[Post]:
        """Get the current content feed for an agent."""

    @abstractmethod
    async def post(self, agent_username: str, content: str, metadata: dict | None = None) -> Post:
        """Agent creates a new post."""

    @abstractmethod
    async def comment(self, agent_username: str, post_id: str, content: str) -> Comment:
        """Agent comments on a post."""

    @abstractmethod
    async def react(self, agent_username: str, post_id: str, reaction: ReactionType) -> None:
        """Agent reacts to a post."""

    @abstractmethod
    def get_state_snapshot(self) -> dict:
        """Return current platform state for streaming visualizer."""
