from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator
from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel


class ReactionType(StrEnum):
    LIKE = "like"
    LOVE = "love"
    HAHA = "haha"
    WOW = "wow"
    SAD = "sad"
    ANGRY = "angry"
    DISLIKE = "dislike"
    REPOST = "repost"
    SHARE = "share"
    UPVOTE = "upvote"
    DOWNVOTE = "downvote"
    AWARD = "award"


class Post(BaseModel):
    id: str
    platform: str
    author_username: str
    content: str
    created_at: datetime
    metadata: dict = {}


class Comment(BaseModel):
    id: str
    post_id: str
    platform: str
    author_username: str
    content: str
    parent_comment_id: str | None = None
    created_at: datetime


class SimulationEvent(BaseModel):
    event_type: str  # post | comment | react | dm

    # The agent's database id. This is what attributes an event to an agent.
    #
    # `agent_username` is a display handle generated by an LLM and is NOT an
    # identity. Asked for 100 handles the model returned 45 distinct ones — nine
    # agents called `mchen_itdir` — and because the runner mapped events back
    # through the username, all nine agents' events landed on one row and nine
    # independent observations counted as one in every confidence interval.
    #
    # Uniqueness is now enforced at generation and by a database constraint, but
    # identity does not depend on that holding: it rides on the id.
    agent_id: str | None = None
    agent_username: str

    platform: str
    round_number: int
    variant: str
    content: str | None = None
    target_id: str | None = None
    metadata: dict = {}
    timestamp: datetime


class BasePlatformAdapter(ABC):
    platform_id: str = ""
    platform_name: str = ""
    supports_reactions: bool = True
    supports_dms: bool = False
    max_post_length: int = 1000
    max_comment_length: int = 500

    # Agent memory: tracks each agent's actions across rounds
    _agent_history: dict[str, list[str]]

    # What the simulation is about. Empty until set_topic() is called.
    _topic: str = ""

    # Material the team published alongside the subject, in the inoculation
    # loop's re-simulation. Empty on every ordinary run.
    _pre_positioned: str = ""

    def _init_history(self) -> None:
        self._agent_history = {}

    def set_topic(self, config: dict) -> None:
        """Capture the simulation's subject and any pre-positioned material.

        Both arrive through the run config, and both are read by
        `topic_block()`, which every adapter already calls. That is deliberate:
        the inoculation loop needed the assets in front of all twelve adapters,
        and adding a hook to twelve `initialize` implementations is twelve
        chances to miss one.
        """
        config = config or {}
        self._topic = config.get("prediction_goal", "") or ""
        self._pre_positioned = config.get("pre_positioned", "") or ""

    def topic_block(self, feed_is_empty: bool = False) -> str:
        """The subject line every action prompt must carry.

        Until this existed, no adapter told its agents what the simulation was
        about: `prediction_goal` was stored in `self._config` by all twelve and
        read by none. The topic reached agents only through the persona bio,
        which is generated from it — so the simulation depended on the bio
        generator succeeding, and produced silent agents when it did not.

        The empty-feed nudge is the other half. On round one nobody has posted,
        and "observe before engaging" is what a careful person actually does —
        so every agent picks NOTHING, the feed stays empty, and the run
        deadlocks at zero events for however many rounds it was given.
        """
        if not self._topic:
            return ""
        block = f"The conversation is about: {self._topic.strip()}\n\n"
        # Pre-positioned, not posted. The material is published alongside the
        # subject and available to every agent from round one, which is what
        # "pre-position this before launch" actually means. Injecting it as a
        # feed post would model somebody dropping the FAQ into the thread — a
        # different intervention, reaching only the agents whose feed slice
        # happened to include it.
        if self._pre_positioned:
            block += self._pre_positioned
        if feed_is_empty:
            block += (
                "The feed is empty — you are among the first to react. Do not "
                "wait for someone else to start; POST your own reaction to the "
                "subject above.\n\n"
            )
        return block

    def record_action(self, agent_key: str, round_num: int, summary: str) -> None:
        """Record an agent's action for memory across rounds.

        `agent_key` must be the agent's **id**, not its username. Keying memory
        on a display handle let colliding agents read each other's history —
        nine agents sharing one handle shared one memory and behaved as a single
        confused actor.
        """
        self._agent_history.setdefault(agent_key, []).append(f"[R{round_num}] {summary}")

    def get_agent_memory(self, agent_key: str, max_items: int = 10) -> str:
        """Formatted history of one agent's previous actions. Keyed on id."""
        history = self._agent_history.get(agent_key, [])
        if not history:
            return ""
        recent = history[-max_items:]
        return "Your previous actions:\n" + "\n".join(recent) + "\n\n"

    @staticmethod
    def agent_key(agent: dict) -> str:
        """Stable identity for an agent dict handed to an adapter.

        Falls back to the username only when no id was supplied, which happens
        in adapter unit tests and nowhere in the live pipeline.
        """
        return agent.get("agent_id") or agent.get("username", "")

    @staticmethod
    def post_ref(raw: object) -> str:
        """A post id an agent typed back, stripped of what it wrapped around it.

        **Every adapter renders its feed as `[<id>] @author: text` and then asks
        for `COMMENT <post_id>: …`. The model copies the id along with the
        brackets it was shown in — inconsistently.** So `post_id` arrives as
        `[a1b2c3]` about four times in five and as `a1b2c3` the rest, and every
        `if p.id == post_id` in this package silently fails on the first form.

        The consequences were live for the whole of V1: reactions never found
        their post, so `upvotes`/`likes` never incremented, so `_hot_score`
        ranked every feed by recency alone. Nothing errored. The feed simply was
        not the feed the design describes, on every run ever made.

        Found on 2026-08-04 by the first run that compared a reference against a
        stored id — 193 of 193 replies failed to resolve — which is the general
        lesson: a value nothing checks is a value nothing is enforcing.

        Use this at the point an id arrives from a model, before comparing it to
        anything.
        """
        return str(raw or "").strip("[]()<>{}\"'`,.:;! \t\n")

    @abstractmethod
    async def initialize(self, config: dict, agents: list) -> None:
        """Set up platform state, assign agents."""

    @abstractmethod
    async def run_round(self, round_number: int) -> AsyncGenerator[SimulationEvent, None]:
        """Execute one simulation round. Yields events as they occur."""

    @abstractmethod
    async def get_feed(self, agent_username: str) -> list[Post]:
        """Get the current content feed for an agent."""

    @abstractmethod
    async def post(self, agent_username: str, content: str, metadata: dict | None = None) -> Post:
        """Agent creates a new post."""

    @abstractmethod
    async def comment(self, agent_username: str, post_id: str, content: str) -> Comment:
        """Agent comments on a post."""

    @abstractmethod
    async def react(self, agent_username: str, post_id: str, reaction: ReactionType) -> None:
        """Agent reacts to a post."""

    @abstractmethod
    def get_state_snapshot(self) -> dict:
        """Return current platform state for streaming visualizer."""
