import { CHART_COLORS, sentimentBarColor } from '@/lib/constants';

interface SentimentTimelineProps {
  data?: { time: string; sentiment: number }[];
  /** Bold takeaway headline auto-generated by the LLM, rendered above the chart */
  headline?: string;
}

export default function SentimentTimeline({ data, headline }: SentimentTimelineProps) {
  if (!data || data.length === 0) {
    return (
      <div className="bg-[#111820] border border-[#1B2433] rounded-2xl p-6 mb-6">
        <h3 className="text-[16px] font-bold text-[#E8ECF2] mb-3">Sentiment Over Time</h3>
        <div className="h-40 flex items-center justify-center text-[#5A6578] text-[13px]">
          Timeline data will appear once structured sentiment data is available.
        </div>
      </div>
    );
  }

  const max = Math.max(...data.map((d) => Math.abs(d.sentiment)), 1);

  // Detect the biggest single-step change as the inflection point
  let inflectionIdx = -1;
  let maxDelta = 0;
  for (let i = 1; i < data.length; i++) {
    const delta = Math.abs(data[i].sentiment - data[i - 1].sentiment);
    if (delta > maxDelta) {
      maxDelta = delta;
      inflectionIdx = i;
    }
  }
  // Only annotate if the change is meaningful (> 0.1)
  const showInflection = inflectionIdx > 0 && maxDelta > 0.1;

  return (
    <div className="bg-[#111820] border border-[#1B2433] rounded-2xl p-6 mb-6">
      {headline && (
        <p className="text-[14px] font-bold text-[#E8ECF2] mb-2 leading-snug">{headline}</p>
      )}
      <h3 className="text-[16px] font-bold text-[#E8ECF2] mb-4">Sentiment Over Time</h3>
      <div className="flex items-end gap-1 h-40 relative">
        {data.map((d, i) => {
          const height = (Math.abs(d.sentiment) / max) * 100;
          const barColor = sentimentBarColor(d.sentiment);
          const isInflection = showInflection && i === inflectionIdx;
          return (
            <div key={i} className="flex-1 flex flex-col items-center justify-end h-full relative">
              {isInflection && (
                <div
                  className="absolute -top-1 left-1/2 -translate-x-1/2 text-[8px] font-bold whitespace-nowrap px-1 rounded"
                  style={{ color: CHART_COLORS.negative, background: 'rgba(248,113,113,0.15)' }}
                >
                  {data[i].sentiment > data[i - 1].sentiment ? '↑' : '↓'} {maxDelta.toFixed(2)}
                </div>
              )}
              <div
                className="w-full rounded-t min-h-[2px]"
                style={{
                  height: `${Math.max(height, 2)}%`,
                  backgroundColor: barColor,
                  outline: isInflection ? `2px solid ${CHART_COLORS.negative}` : undefined,
                }}
                title={`${d.time}: ${d.sentiment.toFixed(2)}`}
              />
              <span className="text-[9px] text-[#5A6578] mt-1 truncate w-full text-center">
                {d.time}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}
